version: "3"

services:
    frontend:
        build:
            context: ../
            dockerfile: infra/Dockerfile
            args:
              - API_ADDR=172.21.148.165
        stdin_open: true
        container_name: app-fe
        ports: 
          - "3000:3000"
          - "80:80"
